# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f39c8ed58e03b99cb644ffb00ee179d7"
name = "bulkpilot"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_content,read_customers,read_discounts,read_files,read_inventory,read_locations,read_markets_home,read_metaobjects,read_online_store_navigation,read_orders,read_products,read_shopify_payments_accounts,write_companies,write_content,write_customers,write_discounts,write_files,write_inventory,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
